#!/usr/bin/env bash
python data_utils/scrape_scene_image_Robothor.py \
  --num_process 15 \
  --scenes "FloorPlan_Train1_1,FloorPlan_Train1_2,FloorPlan_Train1_3,FloorPlan_Train1_4,FloorPlan_Train1_5,FloorPlan_Train2_1,FloorPlan_Train2_2,FloorPlan_Train2_3,FloorPlan_Train2_4,FloorPlan_Train2_5,FloorPlan_Train3_1,FloorPlan_Train3_2,FloorPlan_Train3_3,FloorPlan_Train3_4,FloorPlan_Train3_5,FloorPlan_Train4_1,FloorPlan_Train4_2,FloorPlan_Train4_3,FloorPlan_Train4_4,FloorPlan_Train4_5,FloorPlan_Train5_1,FloorPlan_Train5_2,FloorPlan_Train5_3,FloorPlan_Train5_4,FloorPlan_Train5_5,FloorPlan_Train6_1,FloorPlan_Train6_2,FloorPlan_Train6_3,FloorPlan_Train6_4,FloorPlan_Train6_5"

